### ISSUE TITLE
Probar pagar facturas de proveedores y clientes meses después y hacerle retención de ISR.

### ISSUE THREAD

**Issue by herohat** [dgii-ncf-reports/l10n_do_ncf_oca_reports#3]
Probar pagar facturas de proveedores meses después y hacerle retención de ISR y del mismo modo en las facturas de ventas cuando nos retienen y nos pagan meses después.   

En ambos casos se deben montar nuevamente esas facturas en los respectivos 606 y 607 indicando la fecha de pago y la debida retención.

**Comment by jjdelarosa** [comment]
Si Esta revision debemos darle seguimiento,

**Comment by herohat** [comment]
Estoy trabajando en esto.   El detalle del funcionamiento es este:  https://ayuda.dgii.gov.do/dgii/topics/facturas-con-retenciones-no-pagadas-en-la-fechas-que-se-emiten

**Comment by herohat** [comment]
Done.
